name: Create release from tag

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"


jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        ocaml-compiler:
          - 4.14.0
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use OCaml  ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: opam install mirage
      - run: opam exec -- make
      - run: opam exec -- make package
      - name: Publish
        run: >
          gh release create ${{ github.ref_name }}
            --generate-notes xenserver-test-vm.zip
        env:
          GH_TOKEN: ${{ github.token }}
